version: '2'

services:

    aruna_micropub_daemon:
        build: micropub_daemon
        command: php app/run.php cache --rpp 1000
        env_file: ./.env
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna
        links:
            - aruna_queue

    aruna_resize_daemon:
        build: micropub_daemon
        command: php app/run.php resize_photos --forever
        env_file: ./.env
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna

    aruna_webserver:
        build: webserver
        links:
            - aruna_app_server
        ports:
            - "8084:80"
        environment:
            - NGINX_PORT=80
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna

    aruna_app_server:
        build: app_server
        env_file: .env
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna

    aruna_queue:
      image: schickling/beanstalkd
      volumes:
        - /media/jayr/aruna:/media/jayr/aruna
      command: beanstalkd -b /media/jayr/aruna

    aruna_build:
        build: build
        env_file: .env
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna
