version: '2'

services:

    micropub_daemon:
        build: micropub_daemon
        command: php app/run.php cache --forever --rpp 1000
        env_file: ./.env
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna

    webserver:
        build: webserver
        links:
            - app_server
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna

    app_server:
        build: app_server
        env_file: .env
        volumes:
            - ../..:/srv/aruna
            - /media/jayr/aruna:/media/jayr/aruna

    build:
        build: build
        env_file: .env
        volumes:
            - ../..:/srv/aruna
