app_daemon:
    build: pi/app
    env_file: .env
    volumes:
        - ../..:/srv/aruna
        - /media/jayr/aruna:/media/jayr/aruna
    log_driver: syslog
    log_opt:
        tag: aruna

webserver:
    build: pi/webserver
    links:
        - app_server
    ports:
        - "4567:80"
    environment:
        - NGINX_PORT=80
    log_driver: syslog
    log_opt:
        tag: aruna

app_server:
    build: pi/app_server
    env_file: .env
    volumes:
        - ../..:/srv/aruna
        - /media/jayr/aruna:/media/jayr/aruna
    log_driver: syslog
    log_opt:
        tag: aruna
