#app_daemon:
    #build: app
    #env_file: .env
    #volumes:
        #- ../..:/srv/aruna
        #- /media/jayr/aruna:/media/jayr/aruna

webserver:
    build: webserver
    links:
        - app_server
    ports:
        - "4567:80"
    environment:
        - NGINX_PORT=80
    volumes:
        - ../..:/srv/aruna
        - /media/jayr/aruna:/media/jayr/aruna

app_server:
    build: app_server
    env_file: .env
    volumes:
        - ../..:/srv/aruna
        - /media/jayr/aruna:/media/jayr/aruna

build:
    build: build
    env_file: .env
    volumes:
        - ../..:/srv/aruna
